name: 'Cached NDK install'
description: 'Install NDK and optionally cache it for future use'

inputs:
  ndk-version:
    description: 'NDK version to install'
    required: true
  cached:
    description: 'Whether to cache the NDK'
    required: false
    default: 'false'

runs:
  using: 'composite'
  steps:
    - name: Setup env
      run:
        echo "ANDROID_HOME=$ANDROID_HOME" >> $GITHUB_ENV
      shell: bash

    - name: Cache NDK
      if: inputs.cached == 'true'
      id: cache-ndk
      uses: actions/cache@v4
      with:
        path: ${{ env.ANDROID_HOME }}/ndk/${{ inputs.ndk-version }}
        key: ${{ runner.os }}-ndk-${{ inputs.ndk-version }}

    - name: Install NDK
      if: inputs.cached == 'false' || steps.cache-ndk.outputs.cache-hit != 'true'
      env:
        SDKMANAGER: /cmdline-tools/latest/bin/sdkmanager
      run: |
          if [[ "${{ runner.os }}" == "Windows" ]]; then
            SDKMANAGER=$(echo "$SDKMANAGER" | tr '/' '\').bat
          fi
            "${ANDROID_HOME}${SDKMANAGER}" --install "ndk;${{ inputs.ndk-version }}"
      shell: bash