name: CI

# Controls when the action will run. Triggers the workflow on push or pull
# request events, but only for the `master` branch (generally) or the `citest`
# branch (for testing).
on:
  push:
    branches: [main, citest]
  pull_request:
    branches: [main]

jobs:
  generate_versions:
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE for the job.
      - uses: actions/checkout@v4

      - name: Gradle cache
        uses: gradle/actions/setup-gradle@v3
        with:
          cache-read-only: false

      - name: Gradle test
        run: |
          ./gradlew -p plugin generateTestTasksJson --build-cache 

      - id: setup-matrix
        run: echo "matrix=$(cat plugin/build/build-resources/androidTestTasks.json)" >> "$GITHUB_OUTPUT"

      - name: debug
        run: echo ${{ steps.setup-matrix.outputs.matrix }}

    outputs:
      matrix: ${{ steps.setup-matrix.outputs.matrix }}

  samples:
    # The type of runner that the job will run on
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
          - windows-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE for the job.
      - uses: actions/checkout@v4

      - name: Setup Rust stable
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: x86_64-linux-android,x86_64-unknown-linux-gnu,aarch64-linux-android

      - name: Setup Android NDK (r21e)
        uses: ./.github/actions/cached-ndk
        with:
          ndk-version: '21.4.7075529'

      - name: Setup Android NDK (r23b)
        uses: ./.github/actions/cached-ndk
        with:
          ndk-version: '23.1.7779620'

      - name: Setup Java 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 17

      - name: Gradle cache
        uses: gradle/actions/setup-gradle@v3

      - name: Rust cache
        uses: Swatinem/rust-cache@v2
        with:
          workspaces: |
            samples/rust -> samples/rust/targets/base
            samples/rust -> samples/rust/targets/all
            samples/rust -> samples/rust/targets/noDefaultButBar
            samples/rust -> samples/rust/targets/defaultAndBar
          prefix-key: v0-rust-${{ matrix.os }}

      - name: Assemble samples/app
        run: |
          ./gradlew -p samples/app :assemble --info --warning-mode all --build-cache

      - name: Assemble samples/library
        run: |
          ./gradlew -p samples/library :assemble --info --warning-mode all --build-cache

      - name: Run samples/unittest
        run: |
          ./gradlew -p samples/unittest :build --info --warning-mode all --build-cache

      # Work around https://github.com/actions/cache/issues/454.
      - name: Gradle stop
        run: |
          ./gradlew --stop

  android_unversioned_tests:
    # The type of runner that the job will run on
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
          - windows-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE for the job.
      - uses: actions/checkout@v4

      - name: Setup Rust stable
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: x86_64-linux-android,x86_64-unknown-linux-gnu,aarch64-linux-android

      - name: Setup Rust 1.67
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: 1.67
          targets: x86_64-linux-android,x86_64-unknown-linux-gnu,aarch64-linux-android

      - name: Setup Android NDK (r21e)
        uses: ./.github/actions/cached-ndk
        with:
          ndk-version: '21.4.7075529'

      - name: Setup Android NDK (r23b)
        uses: ./.github/actions/cached-ndk
        with:
          ndk-version: '23.1.7779620'

      # Use Java 8
      - name: Setup Java 8
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 8

      - name: Gradle cache
        uses: gradle/actions/setup-gradle@v3

      - name: Rust cache
        uses: Swatinem/rust-cache@v2
        with:
          workspaces: |
            plugin/src/test/resources/rust -> plugin/build/resources/test/target/1.67
          prefix-key: v0-rust-${{ matrix.os }}
          shared-key: test-1.67

      - name: Rust cache
        uses: Swatinem/rust-cache@v2
        with:
          workspaces: |
            plugin/src/test/resources/rust -> plugin/build/resources/test/target/stable
          prefix-key: v0-rust-${{ matrix.os }}
          shared-key: test-stable

      - name: Gradle test
        run: |
          ./gradlew -p plugin test --info --warning-mode all --build-cache

      # Work around https://github.com/actions/cache/issues/454.
      - name: Gradle stop
        run: |
          ./gradlew --stop

  android_version_tests:
    needs: [generate_versions] # , sanity_check]

    # The type of runner that the job will run on
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
          - windows-latest
        androidTestTask: ${{ fromJson(needs.generate_versions.outputs.matrix) }}

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      - name: Setup Android NDK (r21e)
        uses: ./.github/actions/cached-ndk
        with:
          ndk-version: '21.4.7075529'

      - name: Setup Android NDK (r23b)
        uses: ./.github/actions/cached-ndk
        with:
          ndk-version: '23.1.7779620'

      - name: Setup Rust stable
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: x86_64-linux-android,x86_64-unknown-linux-gnu,aarch64-linux-android

      - name: Setup Rust 1.67
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: 1.67
          targets: x86_64-linux-android,x86_64-unknown-linux-gnu,aarch64-linux-android

      # Use Java 8 globally and Java 11/17 for tests
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: |
            11
            17
            8

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3

      - name: Rust cache
        uses: Swatinem/rust-cache@v2
        with:
          workspaces: |
            plugin/src/test/resources/rust -> plugin/build/resources/test/target/1.67
          prefix-key: v0-rust-${{ matrix.os }}
          shared-key: test-1.67

      - name: Rust cache
        uses: Swatinem/rust-cache@v2
        with:
          workspaces: |
            plugin/src/test/resources/rust -> plugin/build/resources/test/target/null
          prefix-key: v0-rust-${{ matrix.os }}
          shared-key: test-null

      - name: Rust cache
        uses: Swatinem/rust-cache@v2
        with:
          workspaces: |
            plugin/src/test/resources/rust -> plugin/build/resources/test/target/stable
          prefix-key: v0-rust-${{ matrix.os }}
          shared-key: test-stable

      - name: Gradle test
        run: |
          ./gradlew -p plugin ${{ matrix.androidTestTask }} --info --warning-mode all --build-cache

      # Work around https://github.com/actions/cache/issues/454.
      - name: Gradle stop
        run: |
          ./gradlew --stop
